name: CI/CD Pipeline

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Build and Test
        working-directory: ./coursera-spring-hello-world
        run: |
          # Build image
          docker build -t spring-boot-app:latest .
          
          # Run and test in one go
          docker run -d -p 8080:8080 --name spring-app spring-boot-app:latest
          sleep 20
          
          echo "Testing API..."
          curl -f http://localhost:8080/greeting
          
          # Cleanup
          docker rm -f spring-app
